// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTiVLl8qtc0oGamBBgWgwK156fGlWvafU',
    appId: '1:387648119247:web:168ee553395547cecd32ba',
    messagingSenderId: '387648119247',
    projectId: 'dietbot-30cf0',
    authDomain: 'dietbot-30cf0.firebaseapp.com',
    storageBucket: 'dietbot-30cf0.appspot.com',
    measurementId: 'G-7RNSBB0G71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Olxt_f_1Vcf0fElCMHixnGKdVM3Os7k',
    appId: '1:387648119247:android:714f3ebdebdcc448cd32ba',
    messagingSenderId: '387648119247',
    projectId: 'dietbot-30cf0',
    storageBucket: 'dietbot-30cf0.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEB7Oo02fqv2iHZDGw4YkJKVGoZ4fYnfM',
    appId: '1:387648119247:ios:73786330e5ae5847cd32ba',
    messagingSenderId: '387648119247',
    projectId: 'dietbot-30cf0',
    storageBucket: 'dietbot-30cf0.appspot.com',
    iosBundleId: 'com.example.mybot.RunnerTests',
  );
}
